server:
  port: 9090
  servlet:
    context-path: /
spring:
  application:
    name: oil_1201
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/oil?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
    test-while-idle: true
    validation-query: SELECT 1
  mvc:
    static-path-pattern: /**

  resources:
    static-locations: classpath:/static/
  thymeleaf:
    prefix: classpath:/templates/
    check-template-location: true
    cache: false
    suffix: .html #模板后缀
    encoding: UTF-8 #编码
    mode: HTML #模板
    servlet:
      content-type: text/html

mybatis:
  type-aliases-package: com.yangtze.laboratory.oil.pojo
  mapper-locations: classpath:mybatis/com/yangtze/laboratory/oil/*.xml
  config-location: classpath:mybatis/mybatis-config.xml